---
title: Homelab
favicon: https://gethomepage.dev/img/favicon.ico

background:
  image: https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=2400&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 65

layout:
  Media:
    style: row
    columns: 3
  Library:
    style: row
    columns: 3
  Downloads:
    style: row
    columns: 2
  Monitoring:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 2

theme: dark
color: slate

iconStyle: gradient
fiveColumns: false
disableCollapse: false
hideVersion: true
