brew "fish"
brew "tmux"
brew "gitui"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "starship"
brew "pyenv"
brew "kubectl"
brew "luarocks"

# Neovim dependencies
brew "ninja" 
brew "libtool" 
brew "automake" 
brew "cmake" 
brew "pkg-config" 
brew "gettext" 
brew "curl"
brew "gnu-sed"
