brew "fish"
brew "tmux"
brew "gitui"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "starship"
brew "pyenv"
brew "kubectl"
brew "luarocks"
brew "node"
cask "the-unarchiver"

tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"

# Neovim build dependencies
brew "ninja" 
brew "libtool" 
brew "automake" 
brew "cmake" 
brew "pkg-config" 
brew "gettext" 
brew "curl"
brew "gnu-sed"
