backup: true
backupDir: ".config.bak"
# baseDir is the base directory for all the subdirectories of dirs.
baseDir:
dirs:
  backend: Coding/Tutero/Backend/
  frontend: Coding/Tutero/Frontend/
  infrastructure: Coding/Tutero/Infrastructure/
  playground: Coding/Playground/
