#!/opt/homebrew/bin/fish

if type -q fisher
    echo Fisher already installed
    exit 0
end
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

# Dependencies
fisher install PatrickF1/fzf.fish
fisher install edc/bass
fisher install franciscolourenco/done
fisher install jorgebucaran/nvm.fish
fisher install markcial/upto
fisher install meaningful-ooo/sponge
