#!/usr/bin/env python3
"""build_index — regenerate a docs index page from frontmatter.

Greenfield/Fumadocs-native variant of the trading vault's build_index: scans a
content dir for `.md`/`.mdx` with frontmatter, groups by `type:`, sorts by
status/date/title, and writes `<content>/00-INDEX.mdx` with STANDARD markdown
links (`[title](/docs/slug)`) — not Obsidian wikilinks.

Usage (run from the docs/ app dir):
    python3 mdx-plugins/build_index.py [content_dir] [base_url]
    # defaults: content_dir=content/docs  base_url=/docs

No third-party deps (minimal YAML frontmatter parser). Never edits the docs
themselves; only rewrites the index. See content/docs/CONVENTIONS.md.
"""
from __future__ import annotations

import pathlib
import re
import sys
from collections import defaultdict
from typing import Optional

CONTENT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "content/docs").resolve()
BASE_URL = (sys.argv[2] if len(sys.argv) > 2 else "/docs").rstrip("/")
INDEX_NAME = "00-INDEX.mdx"

TYPE_ORDER = ["architecture", "decision", "glossary", "runbook"]
TYPE_TITLES = {
    "architecture": "Architecture",
    "decision": "Decisions (ADRs)",
    "glossary": "Glossary",
    "runbook": "Runbooks",
}
STATUS_ORDER = ["active", "draft", "settled", "superseded", "stale"]


def parse_frontmatter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    out: dict = {}
    current_key: Optional[str] = None
    for line in m.group(1).splitlines():
        if line.startswith("- ") and current_key:
            out[current_key].append(line[2:].strip().strip("\"'"))
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        if value == "":
            out[key] = []
            current_key = key
        elif value.startswith("[") and value.endswith("]"):
            out[key] = [s.strip().strip("\"'") for s in value[1:-1].split(",") if s.strip()]
            current_key = None
        else:
            out[key] = value.strip("\"'")
            current_key = None
    return out


def slug_path(path: pathlib.Path) -> str:
    rel = path.relative_to(CONTENT).with_suffix("")
    parts = list(rel.parts)
    if parts and parts[-1].lower() in ("index", "readme"):
        parts = parts[:-1]
    return "/".join(parts)


def link(path: pathlib.Path, fm: dict) -> str:
    title = fm.get("title") or path.stem
    url = f"{BASE_URL}/{slug_path(path)}".rstrip("/")
    return f"[{title}]({url})"


def first_line(path: pathlib.Path) -> str:
    text = path.read_text()
    m = re.match(r"^---\n.*?\n---\n", text, re.DOTALL)
    body = text[m.end():] if m else text
    in_fence = False
    for raw in body.splitlines():
        if raw.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("<!--"):
            continue
        if len(line) > 160:
            line = line[:157] + "…"
        return line
    return ""


def iter_docs():
    for p in sorted(CONTENT.rglob("*")):
        if p.suffix not in (".md", ".mdx"):
            continue
        if p.name == INDEX_NAME:
            continue
        fm = parse_frontmatter(p.read_text())
        if fm:
            yield p, fm


def sort_key(entry):
    path, fm = entry
    status = fm.get("status", "active")
    s_idx = STATUS_ORDER.index(status) if status in STATUS_ORDER else 99
    date = fm.get("date", "")
    return (s_idx, _neg_date(date), (fm.get("title") or path.stem).lower())


def _neg_date(date: str) -> str:
    try:
        y, m, d = (int(x) for x in date.split("-"))
        return f"-{y:04d}-{m:02d}-{d:02d}"
    except Exception:
        return "0"


def render() -> str:
    by_type = defaultdict(list)
    for path, fm in iter_docs():
        by_type[fm.get("type", "unknown")].append((path, fm))

    out = [
        # frontmatter MUST be line 1 — the generated-marker comment goes in the body
        "---",
        "title: Index",
        "type: glossary",
        "status: active",
        "tags: [index, generated]",
        "---",
        "",
        "{/* generated by the docs-sync skill; edit frontmatter and re-run — do not hand-edit */}",
        "",
        "# Index",
        "",
        "Generated from frontmatter by the **docs-sync** skill. Normative `SHALL`",
        "requirements live in `openspec/specs/`; this is the prose layer.",
        "",
    ]
    for typ in TYPE_ORDER + [t for t in by_type if t not in TYPE_ORDER]:
        entries = by_type.get(typ, [])
        if not entries:
            continue
        out.append(f"## {TYPE_TITLES.get(typ, typ.title())}")
        out.append("")
        for path, fm in sorted(entries, key=sort_key):
            status = fm.get("status", "active")
            date = f" · {fm['date']}" if fm.get("date") else ""
            descr = first_line(path)
            line = f"- {link(path, fm)} — `{status}`{date}"
            if descr:
                line += f". {descr}"
            out.append(line)
        out.append("")
    return "\n".join(out)


def main() -> int:
    if not CONTENT.is_dir():
        print(f"content dir not found: {CONTENT}", file=sys.stderr)
        return 2
    text = render()
    if not text.endswith("\n"):
        text += "\n"
    (CONTENT / INDEX_NAME).write_text(text)
    print(f"wrote {CONTENT / INDEX_NAME}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
