#!/usr/bin/env bash
# gen-depgraph — produce a layer-coloured dependency-graph SVG for a repo.
#   Rust  : cargo-depgraph (workspace) -> colour_depgraph.py -> dot
#   Node  : madge (src) -> dot
# usage: gen-depgraph.sh [repo-root] [out-svg]
#   defaults: repo-root=$PWD  out=<repo>/docs/content/docs/architecture/dep-graph.svg
set -euo pipefail
REPO="${1:-$PWD}"
OUT="${2:-$REPO/docs/content/docs/architecture/dep-graph.svg}"
HERE="$(cd "$(dirname "$0")" && pwd)"

command -v dot >/dev/null || { echo "graphviz 'dot' required (brew install graphviz)"; exit 1; }
mkdir -p "$(dirname "$OUT")"
cd "$REPO"

if [ -f Cargo.toml ]; then
  command -v cargo-depgraph >/dev/null || { echo "needs: cargo install cargo-depgraph"; exit 1; }
  cargo depgraph --workspace-only > /tmp/dg.dot
  if [ -f "$HERE/colour_depgraph.py" ]; then
    python3 "$HERE/colour_depgraph.py" /tmp/dg.dot > /tmp/dg.col.dot 2>/dev/null || cp /tmp/dg.dot /tmp/dg.col.dot
  else
    cp /tmp/dg.dot /tmp/dg.col.dot
  fi
  dot -Tsvg /tmp/dg.col.dot -o "$OUT"
elif [ -f package.json ]; then
  SRC="src"; [ -d "$SRC" ] || SRC="."
  # madge --image renders via graphviz itself and escapes DOT correctly — more
  # robust than `madge --dot | dot` on big/odd trees. Excludes build artifacts.
  npx --yes madge --extensions ts,tsx,js,jsx,mjs,cjs \
    --exclude '(^|/)(node_modules|dist|build|out|\.next|\.source|coverage|public)(/|$)' \
    --image "$OUT" "$SRC" >/dev/null 2>&1
else
  echo "unknown project: no Cargo.toml or package.json at $REPO"; exit 1
fi
echo "wrote $OUT"

# Self-wire: embed the graph in the sibling architecture index if not already there.
IDX="$(dirname "$OUT")/index.mdx"
if [ -f "$IDX" ] && ! grep -q 'dep-graph.svg' "$IDX"; then
  printf '\n## Dependency graph\n\nAuto-generated by docs-sync — the live structural map, coloured by module.\n\n![Dependency graph](./dep-graph.svg)\n' >> "$IDX"
  echo "embedded dep-graph reference in $IDX"
fi
