require("scrollbar").setup {
  show = false,
  show_in_active_only = true,
  marks = {
    Cursor = {
      text = "•",
      priority = 0,
      color = nil,
      cterm = nil,
      highlight = "Normal",
    },
    Search = {
      text = { "-", "=" },
      priority = 1,
      color = nil,
      cterm = nil,
      highlight = "Search",
    },
    Error = {
      text = { "-", "=" },
      priority = 2,
      color = nil,
      cterm = nil,
      highlight = "DiagnosticVirtualTextError",
    },
    Warn = {
      text = { "-", "=" },
      priority = 3,
      color = nil,
      cterm = nil,
      highlight = "DiagnosticVirtualTextWarn",
    },
    Info = {
      text = { "-", "=" },
      priority = 4,
      color = nil,
      cterm = nil,
      highlight = "DiagnosticVirtualTextInfo",
    },
    Hint = {
      text = { "-", "=" },
      priority = 5,
      color = nil,
      cterm = nil,
      highlight = "DiagnosticVirtualTextHint",
    },
    Misc = {
      text = { "-", "=" },
      priority = 6,
      color = nil,
      cterm = nil,
      highlight = "Normal",
    },
    GitAdd = {
      text = "┆",
      priority = 7,
      color = nil,
      cterm = nil,
      highlight = "GitSignsAdd",
    },
    GitChange = {
      text = "┆",
      priority = 7,
      color = nil,
      cterm = nil,
      highlight = "GitSignsChange",
    },
    GitDelete = {
      text = "▁",
      priority = 7,
      color = nil,
      cterm = nil,
      highlight = "GitSignsDelete",
    },
  },
}
