format = "$directory$character"
right_format = "$all"
add_newline = false

[gcloud]
disabled = true

[character]
success_symbol = "[λ](bold purple)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[π](bold green)"

[line_break]
disabled = true

