#!/usr/bin/env bash
# find "$HOME/.config/yabai" - type f -perm +111 -exec {} \;

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ====== Variables =============================

declare -A gaps
declare -A color

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# ===== Tiling setting =========================

yabai -m config layout bsp

yabai -m config top_padding                 7
yabai -m config bottom_padding              7
yabai -m config left_padding                7
yabai -m config right_padding               7
yabai -m config window_gap                  7

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

# yabai -m config window_border               on
# yabai -m config window_border_width         2
# yabai -m config active_window_border_color  "${color["focused"]}"
# yabai -m config normal_window_border_color  "${color["normal"]}"
# yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.95
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

# yabai -m config mouse_modifier              ctrl
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Spaces =================================

# populate_spaces populates the display $1 with #$2 spaces
# $1: display index
# $2: # desired spaces
# populate_spaces () {
#   current=$(yabai -m query --displays | jq ".[] | select(.index == $1) | .spaces | length")
#   echo "$current on display $1. Desired: $2"
#   if [ -z "$current" ]
#   then
#     echo "Could not find display $1"
#   elif (( $current < $2 ))
#   then
#     let diff=$2-$current
#     for i in $(seq 1 $diff)
#     do
#       yabai -m space --create 1 --display $1
#     done
#   fi
# }
#
# populate_spaces 1 2
# populate_spaces 2 2

yabai -m space 1 --label browser
yabai -m space 2 --label social
yabai -m space 3 --label misc
yabai -m space 4 --label coding

# ===== Rules ==================================

# Ignored apps
yabai -m rule --add label="Finder" app="^Finder$" manage=off sticky=on
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off sticky=on
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off opacity=1.0
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off 
yabai -m rule --add label="Archive Utility" app="^Archive Utility$" manage=off 
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Installer" app="^Installer$" sticky=on manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" sticky=on manage=on
yabai -m rule --add label="Karabiner" app="^Karabiner-Elements$" sticky=on manage=off
yabai -m rule --add label="Pika" app="^Pika.*$" sticky=on manage=off
yabai -m rule --add label="Krisp" app="^krisp" manage=off

yabai -m rule --add label="Firefox" app="Firefox" opacity=1.0 
yabai -m rule --add label="Kitty" app="kitty" native-fullscreen=on 
yabai -m rule --add label="Gather" app="Gather" opacity=1.0
yabai -m rule --add label="Slack" app="Slack" native-fullscreen=on
yabai -m rule --add label="Notion" app="Notion"
